### PR TITLE
fix: Separated justification verification for preVotes from preCommits.

### LINKED ISSUE #797: Separate justifications for preVotes from preCommits on handle catchUp response message.

### PR DESCRIPTION
**Pull request by hMitov**
# Description
Separated justification verification for preVotes and preCommits. Previously, they were verified together as part of a single list. 
Now, we create two distinct justifications—one for preVotes and another for preCommits.

### CODE REVIEW

File: src/main/java/com/limechain/network/protocol/grandpa/GrandpaMessageHandler.java [hunk 1]
```diff
@@ -331,10 +336,26 @@ public void handleCatchUpResponse(PeerId peerId,
...
-            throw new JustificationVerificationException("Justification could not be verified.");
+        CompletableFuture<Boolean> verifiedPreCommitsFuture = asyncExecutor.executeAsync(() ->
+                JustificationVerifier.verify(Justification.fromCatchUpResPreCommits(catchUpResMessage)));
+
+        // Combines verified of preVotes and preCommits - it is true only if both and verified.
+        CompletableFuture<Boolean> verifiedFuture = verifiedPreVotesFuture.thenCombine(verifiedPreCommitsFuture,
+                (preVotes, preCommits) -> preVotes && preCommits);
+
+        try {
+            boolean verified = verifiedFuture.get();
```
Comment (Zurcusa) [inline src/main/java/com/limechain/network/protocol/grandpa/GrandpaMessageHandler.java]:
```suggestion
            boolean verified = verifiedFuture.join();
```

You can use join() to avoid the try catch here.

**Review by Zurcusa — APPROVED** [review]

**Review by Grigorov-Georgi — APPROVED** [review]
