### PR TITLE
fix: babe validators flow

### LINKED ISSUE #422: Consensus integration tests
Consensus is a very important part of the network and to make sure our authoring node is acting exactly the way it is supposed to. Therefore our team will add an abundance of integration tests in order to verify the behaviour.

### PR DESCRIPTION
**Pull request by Grigorov-Georgi**
# Description

This PR refactors the BABE validator logic to enable starting a local network from genesis, ensuring proper block production and sealing from the very first block. The changes are backward-compatible and apply seamlessly when acting as a validator on other networks.

Partially fixes:  https://github.com/LimeChain/Fruzhin/issues/422

## Checklist:
- [X] I have read the [contributing guidelines](https://github.com/LimeChain/Fruzhin/blob/dev/CONTRIBUTING.md).
- [X] My PR title matches the [Conventional Commits spec](https://www.conventionalcommits.org/).
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [X] All new and existing tests passed.

### CODE REVIEW

File: src/main/java/com/limechain/storage/block/state/BlockState.java [hunk 1]
```diff
@@ -53,15 +55,17 @@ public class BlockState extends AbstractState {
...
+    public BlockState(KVRepository<String, Object> db,
+                      GenesisBlockHash genesisBlockHash) {
+
         this.db = db;
-        unfinalizedBlocks = new HashMap<>();
-        justifications = new LinkedHashMap<>();
-        genesisBlockHeader = genesisBlockHash.getGenesisBlockHeader();
+        this.unfinalizedBlocks = new HashMap<>();
+        this.justifications = new LinkedHashMap<>();
+        this.genesisBlockHash = genesisBlockHash;
```
Comment (Zurcusa) [inline src/main/java/com/limechain/storage/block/state/BlockState.java:68]: Doesn't `this` make sense only if the parameter has the same name as the field? I've always seen it as a way to distinguish class fields from parameters. Is there another reason to use it?

**Review by Zurcusa — APPROVED** [review]

**Review by hMitov — APPROVED** [review]

File: src/main/java/com/limechain/storage/block/state/BlockState.java (hunk 1 above)
Comment (Grigorov-Georgi) [reply src/main/java/com/limechain/storage/block/state/BlockState.java:68]: I like to follow the rule that if one variable requires ```this```., then all of them should use it for consistency and better visual clarity.
