### PR TITLE
Implemented verify slot winner and fixed network

### LINKED ISSUE #556: EPIC: Implement verify slot winner
As we have already implemented VRF functionality before we should first check what portion of it could be reused. 
- [x] #385 
- [x] #554 
- [x] #383

### PR DESCRIPTION
**Pull request by osrib**
Implement verify slot winner and fix network block announce pears

## Checklist:
- [x] I have read the [contributing guidelines](https://github.com/LimeChain/Fruzhin/blob/dev/CONTRIBUTING.md).
- [x] My PR title matches the [Conventional Commits spec](https://www.conventionalcommits.org/).
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

File: src/main/java/com/limechain/babe/BlockProductionVerifier.java [hunk 1]
```diff
@@ -0,0 +1,32 @@
...
+public class BlockProductionVerifier {
+
+    private EpochState epochState = AppBean.getBean(EpochState.class);
+
+    public boolean verifySlotWinner(int authorityIndex, BigInteger epochIndex, byte[] randomness, BigInteger slotNumber, VrfOutputAndProof vrfOutputAndProof) {
+        List<Authority> authorities = epochState.getCurrentEpochData().getAuthorities();
+        Authority verifyingAuthority = authorities.get(authorityIndex);
+        TranscriptData transcriptData = Authorship.makeTranscript(randomness, slotNumber, epochIndex);
+        BigInteger threshold = Authorship.calculatePrimaryThreshold(epochState.getCurrentEpochDescriptor().getConstant(), authorities, authorityIndex);
+        var isBelowThreshold = LittleEndianUtils.fromLittleEndianByteArray(vrfOutputAndProof.getOutput()).compareTo(threshold) < 0;
```
Comment (Grigorov-Georgi) [inline src/main/java/com/limechain/babe/BlockProductionVerifier.java:26]:
```
 byte[] vrfBytes = schnorrkel.makeBytes(keyPair, transcript, vrfOutputAndProof);

 if (vrfBytes.length != 16) {
    throw new IllegalArgumentException("VRF byte array must be exactly 16 bytes long");
 }

 var isBelowThreshold = LittleEndianUtils.fromLittleEndianByteArray(vrfBytes).compareTo(threshold) < 0;
``` 
You can take the ```isBelowThreshold``` calculation form the ```Authorship.claimPrimarySlot``` method. The value to be compared with the threshold is actually generated using ```Schnorrkel.makeBytes()```, rather than directly using the VrfOutput, as I recall.

**Review by Grigorov-Georgi — CHANGES_REQUESTED** [review]

**Review by Grigorov-Georgi — APPROVED** [review]
