### PR TITLE
fix: grandpa validator's workflow

### LINKED ISSUE #422: Consensus integration tests
Consensus is a very important part of the network and to make sure our authoring node is acting exactly the way it is supposed to. Therefore our team will add an abundance of integration tests in order to verify the behaviour.

### PR DESCRIPTION
**Pull request by Grigorov-Georgi**
# Description

This PR refactors the Grandpa validator logic to enable starting a local network from the genesis, ensuring proper processing of grandpa rounds. The changes are backward-compatible and apply seamlessly when acting as a validator on other networks.

Partially fixes: https://github.com/LimeChain/Fruzhin/issues/422

## Checklist:
- [x] I have read the [contributing guidelines](https://github.com/LimeChain/Fruzhin/blob/dev/CONTRIBUTING.md).
- [x] My PR title matches the [Conventional Commits spec](https://www.conventionalcommits.org/).
- [ ] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Review by hMitov — APPROVED** [review]

File: src/main/java/com/limechain/consensus/grandpa/GrandpaService.java [hunk 1]
```diff
@@ -64,16 +67,23 @@ public GrandpaRound createInitialRound(RoundState roundState) {
...
+        );
     }
 
     public Optional<GrandpaAuthoritySet> getAuthoritiesForBlock(BigInteger blockNumber) {
         GrandpaAuthoritySet authorities = null;
 
         GrandpaSetState grandpaSetState = stateManager.getGrandpaSetState();
 
+        // On the genesis we have empty set changes collection, so we should take the authorities from the chain spec
+        if (grandpaSetState.getSetChanges().isEmpty()) {
```
Comment (Zurcusa) [inline src/main/java/com/limechain/consensus/grandpa/GrandpaService.java]: We should check if we're in set 0 (genesis set). If we don't this could hide potential issues if we don't populate the `setChanges` correctly.

File: src/main/java/com/limechain/consensus/grandpa/round/GrandpaRound.java [hunk 2]
```diff
@@ -232,6 +230,9 @@ public synchronized void update(boolean isPrevRoundChanged,
 
         if (previous != null) {
             shouldStartNextRound = previous.finalizedBlock != null;
+        } else {
+            // at the genesis -> round number is equal to one
+            shouldStartNextRound = roundNumber.equals(BigInteger.ONE);
```
Comment (Zurcusa) [inline src/main/java/com/limechain/consensus/grandpa/round/GrandpaRound.java]: We have rounds with number 1 in every set. This logic would start R + 1 at every first round of a set. We should check if we're in genesis set 0 here as well. Maybe have a utility method that checks if the round's setId is 0.

File: src/main/java/com/limechain/consensus/grandpa/round/GrandpaRound.java [hunk 3]
```diff
@@ -442,8 +476,12 @@ void attemptToFinalize() {
                 blockHeaders.removeFirst();
             }
 
-            blockState.finalizeBlock(finalizedBlock, createJustification(), authoritySet.getSetId());
-            syncState.finalizeBlock(finalizedBlock);
+            try {
+                blockState.finalizeBlock(finalizedBlock, createJustification(), authoritySet.getSetId());
+                syncState.finalizeBlock(finalizedBlock);
+            } catch (BlockStorageGenericException e) {
+                log.warning("Block cannot be finalized: " + e.getMessage());
```
Comment (Zurcusa) [inline src/main/java/com/limechain/consensus/grandpa/round/GrandpaRound.java]:
```suggestion
                log.warning(String.format("Block cannot be finalized: %s", e.getMessage());
```

**Review by Zurcusa — APPROVED** [review]
