### PR TITLE
Fix error starting node

### LINKED ISSUE #279: Error while starting node

### PR DESCRIPTION
**Pull request by ablax**
Closes #279

### CODE REVIEW

File: src/main/java/com/limechain/storage/block/BlockState.java [hunk 1]
```diff
@@ -774,14 +774,18 @@ public void setFinalizedHash(final Hash256 hash, final BigInteger round, final B
...
+            final BigInteger highestSetID = highestRoundAndSetID.getValue1();
 
-        if (setId.compareTo(highestSetID) < 0) {
-            throw new BlockNodeNotFoundException("SetID " + setId + " should be greater or equal to " + highestSetID);
+            if (setId.compareTo(highestSetID) < 0) {
+                throw new BlockStorageGenericException(
+                        "SetID " + setId + " should be greater or equal to " + highestSetID);
+            }
+        } catch (RoundAndSetIdNotFoundException e) {
+            db.save(DBConstants.HIGHEST_ROUND_AND_SET_ID_KEY, helper.bigIntegersToByteArray(round, setId));
```
Comment (stoyan-lime) [inline src/main/java/com/limechain/storage/block/BlockState.java]: With this change do we save the new setId, when it is greater than the old one?

Comment (ablax) [reply src/main/java/com/limechain/storage/block/BlockState.java]: Yes

**Review by vikinatora — APPROVED** [review]
