### PR TITLE
chore: fix warp sync on full node

### LINKED ISSUE #367: Runtime build fails after warp sync

### PR DESCRIPTION
**Pull request by ablax**
# Description

- What does this PR do?
Remove errors if warp syncing

Fixes #367

## Checklist:
- [x] I have read the [contributing guidelines](../CONTRIBUTING.md).
- [x] My PR title matches the [Conventional Commits spec](https://www.conventionalcommits.org/).
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

File: src/main/java/com/limechain/network/protocol/blockannounce/BlockAnnounceEngine.java [hunk 1]
```diff
@@ -78,7 +79,11 @@ private void handleBlockAnnounce(byte[] msg, PeerId peerId) {
                             " stateRoot:" + announce.getHeader().getStateRoot());
 
         if (BlockState.getInstance().isInitialized()) {
-            BlockState.getInstance().addBlock(new Block(announce.getHeader(), new BlockBody(new ArrayList<>())));
+            try {
+                BlockState.getInstance().addBlock(new Block(announce.getHeader(), new BlockBody(new ArrayList<>())));
+            } catch (BlockNodeNotFoundException ignored) {
+                //ignored
+            }
```
Comment (vikinatora) [inline src/main/java/com/limechain/network/protocol/blockannounce/BlockAnnounceEngine.java]: Can we add a comment on why it's ignored?

**Review by vikinatora — APPROVED** [review]
