### PR TITLE
fix: use decoded value if it's hashed

### LINKED ISSUE #367: Runtime build fails after warp sync

### PR DESCRIPTION
**Pull request by ablax**
# Description

- What does this PR do?
Fix merkle proof decoding.
- Why are these changes needed?
Runtime was failing to load after warp sync
- How were these changes implemented and what do they affect?
Update the value of the trie node with the decoded value we receive in the proofs

Fixes #367

## Checklist:
- [x] I have read the [contributing guidelines](../CONTRIBUTING.md).
- [x] My PR title matches the [Conventional Commits spec](https://www.conventionalcommits.org/).
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

File: src/main/java/com/limechain/trie/decoded/TrieProofLoader.java [hunk 1]
```diff
@@ -54,6 +54,11 @@ public static void loadProof(Map<String, byte[]> digestToEncoding, Node node) {
             // to true.
             decodedChild.setDirty(true);
 
+            if(decodedChild.isValueHashed() &&
```
Comment (vikinatora) [inline src/main/java/com/limechain/trie/decoded/TrieProofLoader.java:57]:
```suggestion
            if (decodedChild.isValueHashed() &&
```

Comment (vikinatora) [inline src/main/java/com/limechain/trie/decoded/TrieProofLoader.java]:
```suggestion
            if (decodedChild.isValueHashed() &&
```

**Review by vikinatora — APPROVED** [review]
